language: scala
scala:
   - 2.9.2
jdk:
  - openjdk7
before_script:
  - psql -c 'create database breakpoint;' -U postgres
  - cp conf/application.conf.dist conf/application.conf
  - sed -i 's/db.default.user=breakpoint/db.default.user=postgres/' conf/application.conf
  - sed -i 's/breakpoint.frontend.authentication.send_welcome_email=true/breakpoint.frontend.authentication.send_welcome_email=false/' conf/application.conf
  - echo -e '\napplyEvolutions.default=true' | tee --append conf/application.conf
notifications:
  webhooks:
    - http://rcmp.programble.co.cc/irc.tenthbit.net/programming
    - http://rcmp.programble.co.cc/irc.freenode.net/breakpoint-eval
