language: scala
scala:
  - 2.9.1
jdk:
  - openjdk7
  - oraclejdk7
before_script:
  - psql -c 'create database breakpoint;' -Upostgres
  - cp conf/application.conf.dist conf/application.conf
notifications:
  irc: "irc.freenode.net#breakpoint-eval"

  webhooks:
    - "http://rcmp.tenthbit.net/irc.tenthbit.net/programming"
